name: Auto districting update
on:
  schedule:
    - cron: "0 21 * * 0"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run auto districting
        env:
          ESTAT_API_KEY: ${{ secrets.ESTAT_API_KEY }}
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          mkdir -p outputs/$DATE
          python src/main.py
          cp outputs/*.csv outputs/$DATE/ || true
          cp outputs/*.png outputs/$DATE/ || true
          cp outputs/*.html outputs/$DATE/ || true
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add outputs || true
          git commit -m "Auto update $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./outputs
